import TopNavigation from "@/components/layout/top-navigation";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Electrify",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <section>
      <TopNavigation />
      {children}
    </section>
  );
}
